### ISSUE TITLE
Site loads from browser cache where the code is not always up to date

### ISSUE THREAD

**Issue by floatingturnip** [ubcengfizz/fizz#2]
Currently there's an issue where if a user has visited the site before, the site may load information from an older version of the code, thus they can't see the new changes to the site without clearing their browser cache

**Comment by HXavS** [comment]
Looks like cache expires after 5 mins (600 seconds) 
You can add a query string to the urls and populate it with a version number so that when you call 
https://www.ubcfizz.com/static/js/2.5f49d924.chunk.js it is https://www.ubcfizz.com/static/js/2.5f49d924.chunk.js?v=1.2.1

When you update the v= the server will ignore the query but browser will see it as a new file a request the file again even though the contents could be the same.

**Comment by HXavS** [comment]
Also you have a 404 for the https://www.ubcfizz.com/favicon.ico asset.

**Comment by floatingturnip** [comment]
Thanks for the information! Realized our issue was also partly due to needing to build and deploy.
